### PR TITLE
Signing of LS records

### PR DESCRIPTION
**Pull request by sowmyab**
This allows lsregistrationdaemon to sign and register records.

### CODE REVIEW

**Comment by arlake228** [comment]
Looks pretty good overall, but found a few things:

*  I already took care of this, but I added the new dependencies to the Vagrantfile so it is easy to bring up a new dev environment
* In `etc/lsregistrationdaemon.conf` you should comment-out the signature-related fields since they point at non-existent paths. We want the file to work out of the box so any placeholder like that need to be commented-out
* I noticed the signature related files that are imported from perl-shared are not symlinks, and I think the copies in lsregistrationdaemon may be out of sync with what you have in shared. In particular lib/perfSONAR_PS/Client/LS/PSRecords/PSSignature.pm is out of sync which is causing an error. The shared can be a bit challenging in branches, but you can run the following to get shared to point at your perl shared branch:

```
cd shared
git pull origin sowmya-lsrecord-signing
cd ../lib/perfSONAR_PS/Client/LS/PSRecords/
rm PSSignature.pm
ln -s ../../../../../shared/lib/perfSONAR_PS/Client/LS/PSRecords/PSSignature.pm ./
```

Create symlinks for all the stuff you pulled in from shared and you should be good.

You can then use symlinks to point at the files like the other shared files. 

* I think this is related to last bullet for for completeness, I get the following when I try to start the daemon:

```
The following parameter was passed in the call to SimpleLookupService::Records::Security::Signature::init but was not listed in the validation options: certificate
 at /vagrant/bin/../lib/SimpleLookupService/Records/Security/Signature.pm line 29.
	SimpleLookupService::Records::Security::Signature::init('perfSONAR_PS::Client::LS::PSRecords::PSSignature=HASH(0x4cef540)', 'certificate', '') called at /vagrant/bin/../lib/perfSONAR_PS/Client/LS/PSRecords/PSSignature.pm line 27
	perfSONAR_PS::Client::LS::PSRecords::PSSignature::init('perfSONAR_PS::Client::LS::PSRecords::PSSignature=HASH(0x4cef540)', 'certificate', '') called at /vagrant/bin/../lib/perfSONAR_PS/LSRegistrationDaemon/Signature.pm line 103
	perfSONAR_PS::LSRegistrationDaemon::Signature::build_registration('perfSONAR_PS::LSRegistrationDaemon::Signature=HASH(0x3bbaf58)') called at /vagrant/bin/../lib/perfSONAR_PS/LSRegistrationDaemon/Base.pm line 304
...
```

**Comment by sowmyab** [comment]
I have made the above changes in commit [c094b97](/perfsonar/ls-registration-daemon/pull/56/commits/c094b97a6b8cd2eac4e6f6834be0a5a220d919b5). Let me know if it is okay to merge.

**Comment by arlake228** [comment]
I am still running into uses when running the code. I fixed a small issue with the default config file containing values that look like they leaked in from a dev environment. After doing that though I still run into the following:

```
2019/03/04 19:41:18 (4781) ERROR> lsregistrationdaemon.pl:151 main::__ANON__ - Died: Can't locate object method "setCertificate" via package "perfSONAR_PS::Client::LS::PSRecords::PSHost" at /vagrant/bin/../lib/perfSONAR_PS/LSRegistrationDaemon/Host.pm line 687.
Can't locate object method "setCertificate" via package "perfSONAR_PS::Client::LS::PSRecords::PSHost" at /vagrant/bin/../lib/perfSONAR_PS/LSRegistrationDaemon/Host.pm line 687.
```

I can find a setCertificate subroutine in the referenced classes or its parents. Maybe the change is not committed to your branch in perl-shared? or maybe it is supposed to be operating on a signature object?

**Comment by sowmyab** [comment]
Figured out the issue. The change was made directly in the shared directory of lsregistration daemon instead of changing in the perl-shared project. The issue has been fixed.

**Comment by arlake228** [comment]
Code runs and I am able to register things both with and without the signature. I do have one clarification on the registration format. It appears that all the records have the signature field but only the host has the "certificate" field. Is this intended? A client could still get the certificate by retrieving the host record, but it requires an additional query. I am not saying we need to change it if it is intended, just want to double-check. Example of the records I am seeing are below:

```
[
   {
      "expires":"2019-03-22T16:45:01.623Z",
      "x509certificate":[
         "-----BEGIN CERTIFICATE-----\nMIID0TCCArmgAwIBAgIJAOanAhidXOg4MA0GCSqGSIb3DQEBCwUAMH8xCzAJBgNV\nBAYTAlVTMREwDwYDVQQIDAhNaWNoaWdhbjEPMA0GA1UEBwwGRGV4dGVyMQ4wDAYD\nVQQKDAVFU25ldDEMMAoGA1UECwwDU0VHMRIwEAYDVQQDDAkxMC4wLjAuMjAxGjAY\nBgkqhkiG9w0BCQEWC2FuZHlAZXMubmV0MB4XDTE5MDMyMjE0MzIxNloXDTIwMDMy\nMTE0MzIxNlowfzELMAkGA1UEBhMCVVMxETAPBgNVBAgMCE1pY2hpZ2FuMQ8wDQYD\nVQQHDAZEZXh0ZXIxDjAMBgNVBAoMBUVTbmV0MQwwCgYDVQQLDANTRUcxEjAQBgNV\nBAMMCTEwLjAuMC4yMDEaMBgGCSqGSIb3DQEJARYLYW5keUBlcy5uZXQwggEiMA0G\nCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDXzDuFKe1kQ4B5QBbZIPIb9S66we8u\nkQYcpCeVeSMnxL1fhlSsc6cFj+a3N5NolT2ZODtF1c36CzBYywluk59/pJZQ56Rv\nxtD74lD6/ktkLho682oFVQA1vIfdUgQHeWDTg+CCU4rXF98JQgiP6vigk8FqhUmh\nGiF9q4FimP5wUcX+DS/kEEKgdfbADUqfRZzTKRjfzp6QGUcRSl/GUHmHR6tf7kTU\nP+/udzL3+iU4K7oI6VSZ+LTdyUZNHf2YJERDy2KGFFIgyMqkovQN4yK8ZDOqWxRv\nqFs7pxGGSlt/BDz0OZSYCkihzHU8lip329w8etztOnLcJFoGdztXmzNrAgMBAAGj\nUDBOMB0GA1UdDgQWBBSHB4OvjzubcKTmJZmr6wFEbJvLkzAfBgNVHSMEGDAWgBSH\nB4OvjzubcKTmJZmr6wFEbJvLkzAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBCwUA\nA4IBAQCPGgY69Kky6oBbRHLPof4U7fHOwf3dTu9rke97Rsq4q7vvPdoA8jIlUEcw\n9ZFQfEMTZsb97X7YllWDhK7d0pPKKEfO/ojOARnxWM2h69zieKsYogSWv7AGmjkW\n5fubYKxKuIwRnab54w+jZDRWm7rsY8Ehem5R8BjSWZPTcWK6c0YpXk1ZKb4qbvj0\nkUVAr+YHLjOVZzo5XFwfq0sGKP4Ln6xVP6xHUDMJt7FEGchsI5q1lU3V/ttP1V7H\nROE0a5F7ivw2tTb14Pf4gOwkl2sdJkyngLG9euZp4V69mfM2OKwh0bK+cM8ioJQX\nMPMV3dcGUdNKsSdpMa7UgeXvYceC\n-----END CERTIFICATE-----\n"
      ],
      "signature":[
         "o7wJzhVE8xgHihQKXAT52HNbEGRCkCu+zKNc7kR4mf4q/gqAORZwZj6jplgzzzjbalymr18q9GPh\nwifoVsxHDh7VvuoNTYur9reWqJCVU85Bhvndgx16/kYQo7k+VRwuSO3qFDrEyLBywD+myElmEOTq\nL18ZcxA7P00HXzIaRhbnrFnnMaxDeTLx/ByxdKtJ/1f8z+j/HdO2+21qul7D+u2G6TaFD0GTRC25\nxpENCqGg7xs3ldMB4CuoRs83a5zyq+lsWE6jg5qUz+yW/RkAiAmwKeonyeHRnRrArGjdoFw9qUpF\nAMWkggR4vnIIcuHN5bqR2JQQCTlL9mSUBF2rOQ==\n"
      ],
      "signature-encoding":[
         "base64"
      ],
      "client-uuid":[
         "5C2F85A8-3EB3-11E9-BD36-D009CF8E42C3"
      ],
      "digest":[
         "sha256"
      ],
      "state":"registered",
      "type":[
         "signature"
      ],
      "uri":"lookup/signature/0d59e661-27c7-41c4-ae4d-b107d9b520b4"
   },
   {
      "expires":"2019-03-22T16:45:01.666Z",
      "interface-capacity":[
         "1000000000"
      ],
      "signature":[
         "VKRQZAKoUlhleaf6RVrZWKJFEtlTBSAMuvWER9QJ/J3zWxnjYmuIMKa0d68YUfF0OjXx8QKBZkms\nBVFXng0Mf0q9OTuUGj0xSwVYsXtaownY7coEnFwTQcV87PTxgQ7efyc64hRZ+tREMGuX9saguvAS\n7pEb3Li22/Hq2RJTyYMpokibGfoDl/4eoIE0jLB3If9yrOQEbjLwc7CQtj27T9jryhDAqPlumafr\nc66Wh5tyC6EE18DaYg1pz8ytrYAz5GMEQ94hpiiscXP6ijAAIr9+4AsjSbCskMliqVqDyyjBQEpK\nXAzpRqopa0L27XiwAdsI92VXHcEb3gr7f9ryxw==\n"
      ],
      "interface-name":[
         "eth2"
      ],
      "interface-addresses":[
         "fdac:218a:75e5:69c8::20"
      ],
      "pscheduler-tests":[

      ],
      "interface-mtu":[
         "1500"
      ],
      "interface-mac":[
         "08:00:27:2c:4b:69"
      ],
      "type":[
         "interface"
      ],
      "uri":"lookup/interface/9d98826a-b077-4bea-be28-2b03d6091d34",
      "client-uuid":[
         "5C2F85A8-3EB3-11E9-BD36-D009CF8E42C3"
      ],
      "group-domains":[

      ],
      "state":"registered"
   },
   {
      "host-vm":[
         "1"
      ],
      "host-administrators":[
         ""
      ],
      "expires":"2019-03-22T16:45:01.728Z",
      "host-hardware-processorcore":[
         "1"
      ],
      "signature":[
         "U+igDyssM1vhIgA08Lmw03KSVWoLoovL7ZiAObuESxlfzVjBv0a5qWlDa6qmP+Xh/4cOthG9r48d\nieujCetbOZcNqklViiZTcSOeWCtsdmtBqRw0KdIkzxI4xe2VT1zfWryK2x0o0A+zItFAclHNg7D4\nsO2Vn3WOUwqkCf/n4Zj09q9206t4yX8Zn3EHnNu7ScDPKlVCREifbwhdiVUgi8+mL/4MKrx4oj1t\nc8QLQt3id751HulOJup5h3p0kP+QySj/1GWA+cLVsQc24n+tvnln9cGiL2/EiYTJvn7g6qi6fwiA\nU5j+YqiyVrTizpiSYS5RBIOLiKMV+QPr14z0Kw==\n"
      ],
      "host-os-kernel":[
         "Linux 3.10.0-957.5.1.el7.x86_64"
      ],
      "host-os-name":[
         "CentOS Linux"
      ],
      "certificate":[
         "lookup/signature/0d59e661-27c7-41c4-ae4d-b107d9b520b4"
      ],
      "type":[
         "host"
      ],
      "host-hardware-processorspeed":[
         "2904.000 MHz"
      ],
      "host-os-version":[
         "7.6.1810 (Core) "
      ],
      "host-net-interfaces":[
         "lookup/interface/9d98826a-b077-4bea-be28-2b03d6091d34"
      ],
      "host-productname":[
         "VirtualBox"
      ],
      "client-uuid":[
         "5C2F85A8-3EB3-11E9-BD36-D009CF8E42C3"
      ],
      "state":"registered",
      "host-net-tcp-autotunemaxbuffer-send":[
         "3871840 bytes"
      ],
      "host-net-tcp-maxbuffer-recv":[
         "212992 bytes"
      ],
      "host-manufacturer":[
         "innotek GmbH"
      ],
      "host-hardware-cpuid":[
         "Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz"
      ],
      "host-hardware-processorcount":[
         "1"
      ],
      "host-net-tcp-congestionalgorithm":[
         "cubic"
      ],
      "host-os-architecture":[
         "x86_64"
      ],
      "host-name":[
         "fdac:218a:75e5:69c8::20"
      ],
      "uri":"lookup/host/c180dea4-f6fb-4ef7-a952-a6f0784b7871",
      "host-net-tcp-autotunemaxbuffer-recv":[
         "3871840 bytes"
      ],
      "group-domains":[

      ],
      "host-hardware-memory":[
         "487 MB"
      ],
      "host-net-tcp-maxbuffer-send":[
         "212992 bytes"
      ],
      "host-net-ipv6-enabled":[
         "1"
      ]
   },
   {
      "expires":"2019-03-22T16:45:01.802Z",
      "psservice-eventtypes":[
         "http://ggf.org/ns/nmwg/tools/owamp/1.0"
      ],
      "signature":[
         "JcY3ns+26TBitMFHJ/JgvOcLMdoTjpWPj/4ZHm7CBKUUMs45wu6zR4rfSyP0tRfijt4ULEf3ufqJ\nN0yn2FoSVXYzVyzx8c0gDTNbCwFj73V2oiuoQYjMTTDnijxvuvd4I773EPhghMgZ1N/lgRHEaibh\nnSjHTX3nzGRL29oGiiMEEQqB7pZCTb8DQip8bFFXgcn44bJfLzCrI5oIQ1KsKaRUqGOhSUfZFvyF\nN0TFyJvGJbC92ZXlUSrR/7stBpIXsIk2uzvOxV5nH1mqylIBUEcAjkxhW+1TJ2FRcKQxxgO1Y3LI\neuPrrMHmkIjHsh+f4oGXBi0JZZ5hmtZvUe5DHg==\n"
      ],
      "service-type":[
         "owamp"
      ],
      "type":[
         "service"
      ],
      "uri":"lookup/service/c94b1af5-ba2b-43f2-922a-6ab53d805d1e",
      "service-host":[
         "lookup/host/c180dea4-f6fb-4ef7-a952-a6f0784b7871"
      ],
      "service-name":[
         "OWAMP Server"
      ],
      "client-uuid":[
         "5C2F85A8-3EB3-11E9-BD36-D009CF8E42C3"
      ],
      "group-domains":[

      ],
      "state":"registered",
      "service-administrators":[
         ""
      ],
      "service-locator":[
         "tcp://[fdac:218a:75e5:69c8::20]:861"
      ]
   }
]
```

**Pull request merged**
